// Extracts translatable strings from the plugin and builds languages/*.l10n.php + .po
// Usage: node tools-i18n.mjs            -> build from tools-i18n-de.json
//        node tools-i18n.mjs --missing  -> list strings without German translation
import fs from 'node:fs';
import path from 'node:path';

const ROOT = 'outbox-mail-log';
const DOMAIN = 'outbox-mail-log';
const re = /\b(?:__|_e|esc_html__|esc_html_e|esc_attr__|esc_attr_e)\(\s*'((?:[^'\\]|\\.)*)'\s*,\s*'outbox-mail-log'\s*\)/g;

function walk(dir, out = []) {
	for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
		const p = path.join(dir, e.name);
		if (e.isDirectory()) walk(p, out);
		else if (p.endsWith('.php') && !p.includes('languages')) out.push(p);
	}
	return out;
}

const strings = new Set();
for (const f of walk(ROOT)) {
	for (const m of fs.readFileSync(f, 'utf8').matchAll(re)) strings.add(m[1].replace(/\\'/g, "'"));
}

const de = JSON.parse(fs.readFileSync('tools-i18n-de.json', 'utf8'));
const missing = [...strings].filter((s) => !(s in de));
if (process.argv.includes('--missing')) {
	console.log(missing.join('\n') || '(none)');
	process.exit(0);
}
if (missing.length) {
	console.error('Missing translations:\n' + missing.join('\n'));
	process.exit(1);
}

const sorted = [...strings].sort();
const php = (s) => "'" + s.replace(/\\/g, '\\\\').replace(/'/g, "\\'") + "'";
const po = (s) => '"' + s.replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"';

fs.mkdirSync(path.join(ROOT, 'languages'), { recursive: true });
fs.writeFileSync(
	path.join(ROOT, 'languages', `${DOMAIN}-de_DE.l10n.php`),
	`<?php
// Generated by tools-i18n.mjs – do not edit by hand.
return array(
	'domain'       => '${DOMAIN}',
	'plural-forms' => 'nplurals=2; plural=(n != 1);',
	'language'     => 'de_DE',
	'messages'     => array(
${sorted.map((s) => `\t\t${php(s)} => ${php(de[s])},`).join('\n')}
	),
);
`
);
fs.writeFileSync(
	path.join(ROOT, 'languages', `${DOMAIN}-de_DE.po`),
	'msgid ""\nmsgstr ""\n"Content-Type: text/plain; charset=UTF-8\\n"\n"Language: de_DE\\n"\n' +
		`"Plural-Forms: nplurals=2; plural=(n != 1);\\n"\n"X-Domain: ${DOMAIN}\\n"\n\n` +
		sorted.map((s) => `msgid ${po(s)}\nmsgstr ${po(de[s])}\n`).join('\n')
);
console.log(`${strings.size} strings written.`);
