#!/usr/bin/env node
/**
 * Bundled translations: extracts the plugin's strings and builds languages/*.l10n.php + .po from i18n/<locale>/*.json.
 *
 *   npm run i18n               # rebuild the language files from i18n/<locale>/*.json (one file per module)
 *   npm run i18n -- --check    # CI: fail on missing/unused translations or outdated generated files
 *
 * Plurals: for _n( 'singular', 'plural', $n, … ) both texts are translated as two keys of the JSON files; the
 * generated files combine them into one plural entry (nplurals=2, like English and German).
 *
 * wordpress.org language packs (translate.wordpress.org) take precedence at runtime; the bundled files are
 * the fallback until a language pack exists (see Plugin::load_textdomain()).
 */
import fs from 'node:fs';
import path from 'node:path';
import { PLUGIN_SLUG, pluginDir, root } from './lib/php.mjs';

const check = process.argv.includes('--check');
const re = new RegExp(`\\b(?:__|_e|esc_html__|esc_html_e|esc_attr__|esc_attr_e)\\(\\s*'((?:[^'\\\\]|\\\\.)*)'\\s*,\\s*'${PLUGIN_SLUG}'\\s*\\)`, 'g');
// _n( 'singular', 'plural', <count>, 'slug' ): the count expression may contain parentheses, so it is skipped lazily.
const rePlural = new RegExp(`\\b_n\\(\\s*'((?:[^'\\\\]|\\\\.)*)'\\s*,\\s*'((?:[^'\\\\]|\\\\.)*)'\\s*,[^;]*?'${PLUGIN_SLUG}'\\s*\\)`, 'g');

function walk(dir, out = []) {
	for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
		const p = path.join(dir, e.name);
		if (e.isDirectory()) {
			if (e.name !== 'languages') walk(p, out);
		} else if (p.endsWith('.php')) {
			out.push(p);
		}
	}
	return out;
}

const unescape = (s) => s.replace(/\\'/g, "'");
const strings = new Set(); // every text that needs a translation in the JSON files
const singles = new Set(); // texts used on their own (__, _e, esc_html__ …)
const plurals = new Map(); // _n(): singular => plural
for (const file of walk(pluginDir)) {
	const code = fs.readFileSync(file, 'utf8');
	for (const m of code.matchAll(re)) {
		strings.add(unescape(m[1]));
		singles.add(unescape(m[1]));
	}
	for (const m of code.matchAll(rePlural)) {
		strings.add(unescape(m[1]));
		strings.add(unescape(m[2]));
		plurals.set(unescape(m[1]), unescape(m[2]));
	}
}
const sorted = [...strings].sort();
// Generated entries: plain texts, plus one entry per _n() pair (keys and translations joined by NUL, as
// WP_Translation_File_PHP and gettext expect), sorted by the singular.
const entries = [
	...[...singles].map((s) => ({ key: s, plural: null })),
	...[...plurals].map(([s, p]) => ({ key: s, plural: p })),
].sort((a, b) => (a.key === b.key ? (a.plural ? 1 : -1) : a.key < b.key ? -1 : 1));

const php = (s) => "'" + s.replace(/\\/g, '\\\\').replace(/'/g, "\\'") + "'";
const po = (s) => '"' + s.replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"';

const problems = [];
const files = {};
// i18n/<locale>/*.json – one file per module (core.json, trace.json …), merged here.
for (const locale of fs.readdirSync(path.join(root, 'i18n')).filter((f) => fs.statSync(path.join(root, 'i18n', f)).isDirectory())) {
	const jsonFile = `${locale}/*.json`;
	const map = {};
	for (const part of fs.readdirSync(path.join(root, 'i18n', locale)).filter((f) => f.endsWith('.json')).sort()) {
		for (const [key, value] of Object.entries(JSON.parse(fs.readFileSync(path.join(root, 'i18n', locale, part), 'utf8')))) {
			if (key in map && map[key] !== value) problems.push(`${locale}: "${key}" translated differently in ${part}`);
			map[key] = value;
		}
	}
	for (const s of sorted) if (!(s in map)) problems.push(`${locale}: missing translation for "${s}"`);
	for (const s of Object.keys(map)) if (!strings.has(s)) problems.push(`${locale}: unused translation "${s}"`);

	const done = entries.filter((e) => e.key in map && (!e.plural || e.plural in map));
	const base = path.join(pluginDir, 'languages', `${PLUGIN_SLUG}-${locale}`);
	files[`${base}.l10n.php`] = `<?php
// Generated by scripts/i18n.mjs from i18n/${jsonFile} – do not edit by hand.
return array(
	'domain'       => '${PLUGIN_SLUG}',
	'plural-forms' => 'nplurals=2; plural=(n != 1);',
	'language'     => '${locale}',
	'messages'     => array(
${done.map((e) => (e.plural
		? `\t\t${php(e.key)} . "\\0" . ${php(e.plural)} => ${php(map[e.key])} . "\\0" . ${php(map[e.plural])},`
		: `\t\t${php(e.key)} => ${php(map[e.key])},`)).join('\n')}
	),
);
`;
	files[`${base}.po`] = 'msgid ""\nmsgstr ""\n"Content-Type: text/plain; charset=UTF-8\\n"\n' +
		`"Language: ${locale}\\n"\n"Plural-Forms: nplurals=2; plural=(n != 1);\\n"\n"X-Domain: ${PLUGIN_SLUG}\\n"\n\n` +
		done.map((e) => (e.plural
			? `msgid ${po(e.key)}\nmsgid_plural ${po(e.plural)}\nmsgstr[0] ${po(map[e.key])}\nmsgstr[1] ${po(map[e.plural])}\n`
			: `msgid ${po(e.key)}\nmsgstr ${po(map[e.key])}\n`)).join('\n');
}

if (check) {
	for (const [file, content] of Object.entries(files)) {
		const current = fs.existsSync(file) ? fs.readFileSync(file, 'utf8').replace(/\r\n/g, '\n') : null;
		if (current !== content) problems.push(`${path.relative(root, file)} is outdated – run \`npm run i18n\``);
	}
	if (problems.length) {
		console.error(problems.join('\n'));
		process.exit(1);
	}
	console.log(`i18n: ${strings.size} strings, ${Object.keys(files).length / 2} locale(s) complete and up to date.`);
	process.exit(0);
}

if (problems.length) {
	console.error(problems.join('\n'));
	process.exit(1);
}
fs.mkdirSync(path.join(pluginDir, 'languages'), { recursive: true });
for (const [file, content] of Object.entries(files)) fs.writeFileSync(file, content);
console.log(`${strings.size} strings written for ${Object.keys(files).length / 2} locale(s).`);
