#!/usr/bin/env node
/**
 * Bundled translations: extracts the plugin's strings and builds languages/*.l10n.php + .po from i18n/<locale>/*.json.
 *
 *   npm run i18n               # rebuild the language files from i18n/<locale>/*.json (one file per module)
 *   npm run i18n -- --check    # CI: fail on missing/unused translations or outdated generated files
 *
 * wordpress.org language packs (translate.wordpress.org) take precedence at runtime; the bundled files are
 * the fallback until a language pack exists (see Plugin::load_textdomain()).
 */
import fs from 'node:fs';
import path from 'node:path';
import { PLUGIN_SLUG, pluginDir, root } from './lib/php.mjs';

const check = process.argv.includes('--check');
const re = new RegExp(`\\b(?:__|_e|esc_html__|esc_html_e|esc_attr__|esc_attr_e)\\(\\s*'((?:[^'\\\\]|\\\\.)*)'\\s*,\\s*'${PLUGIN_SLUG}'\\s*\\)`, 'g');

function walk(dir, out = []) {
	for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
		const p = path.join(dir, e.name);
		if (e.isDirectory()) {
			if (e.name !== 'languages') walk(p, out);
		} else if (p.endsWith('.php')) {
			out.push(p);
		}
	}
	return out;
}

const strings = new Set();
for (const file of walk(pluginDir)) {
	for (const m of fs.readFileSync(file, 'utf8').matchAll(re)) strings.add(m[1].replace(/\\'/g, "'"));
}
const sorted = [...strings].sort();

const php = (s) => "'" + s.replace(/\\/g, '\\\\').replace(/'/g, "\\'") + "'";
const po = (s) => '"' + s.replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"';

const problems = [];
const files = {};
// i18n/<locale>/*.json – one file per module (core.json, trace.json …), merged here.
for (const locale of fs.readdirSync(path.join(root, 'i18n')).filter((f) => fs.statSync(path.join(root, 'i18n', f)).isDirectory())) {
	const jsonFile = `${locale}/*.json`;
	const map = {};
	for (const part of fs.readdirSync(path.join(root, 'i18n', locale)).filter((f) => f.endsWith('.json')).sort()) {
		for (const [key, value] of Object.entries(JSON.parse(fs.readFileSync(path.join(root, 'i18n', locale, part), 'utf8')))) {
			if (key in map && map[key] !== value) problems.push(`${locale}: "${key}" translated differently in ${part}`);
			map[key] = value;
		}
	}
	for (const s of sorted) if (!(s in map)) problems.push(`${locale}: missing translation for "${s}"`);
	for (const s of Object.keys(map)) if (!strings.has(s)) problems.push(`${locale}: unused translation "${s}"`);

	const base = path.join(pluginDir, 'languages', `${PLUGIN_SLUG}-${locale}`);
	files[`${base}.l10n.php`] = `<?php
// Generated by scripts/i18n.mjs from i18n/${jsonFile} – do not edit by hand.
return array(
	'domain'       => '${PLUGIN_SLUG}',
	'plural-forms' => 'nplurals=2; plural=(n != 1);',
	'language'     => '${locale}',
	'messages'     => array(
${sorted.filter((s) => s in map).map((s) => `\t\t${php(s)} => ${php(map[s])},`).join('\n')}
	),
);
`;
	files[`${base}.po`] = 'msgid ""\nmsgstr ""\n"Content-Type: text/plain; charset=UTF-8\\n"\n' +
		`"Language: ${locale}\\n"\n"Plural-Forms: nplurals=2; plural=(n != 1);\\n"\n"X-Domain: ${PLUGIN_SLUG}\\n"\n\n` +
		sorted.filter((s) => s in map).map((s) => `msgid ${po(s)}\nmsgstr ${po(map[s])}\n`).join('\n');
}

if (check) {
	for (const [file, content] of Object.entries(files)) {
		const current = fs.existsSync(file) ? fs.readFileSync(file, 'utf8').replace(/\r\n/g, '\n') : null;
		if (current !== content) problems.push(`${path.relative(root, file)} is outdated – run \`npm run i18n\``);
	}
	if (problems.length) {
		console.error(problems.join('\n'));
		process.exit(1);
	}
	console.log(`i18n: ${strings.size} strings, ${Object.keys(files).length / 2} locale(s) complete and up to date.`);
	process.exit(0);
}

if (problems.length) {
	console.error(problems.join('\n'));
	process.exit(1);
}
fs.mkdirSync(path.join(pluginDir, 'languages'), { recursive: true });
for (const [file, content] of Object.entries(files)) fs.writeFileSync(file, content);
console.log(`${strings.size} strings written for ${Object.keys(files).length / 2} locale(s).`);
